apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: ecommerce-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: ecommerce-app
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    # ISSUE #9: Missing "get" verb - only has "list", pod can't read individual secrets
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: ecommerce-app
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: ecommerce-app
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
