{
 "title": "LLM+MCPAgentGateway",
 "time": { "from": "2025-10-19T14:08:04.035Z", "to": "2025-10-19T16:18:34.035Z" },
 "panels": [
  {
   "title": "GenAI Client Token Usage Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "agentgateway_gen_ai_client_token_usage_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GenAI Server Request Duration Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "agentgateway_gen_ai_server_request_duration_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GenAI Client Token Usage Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "agentgateway_gen_ai_client_token_usage_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GenAI Server Request Duration Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "agentgateway_gen_ai_server_request_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GenAI Client Token Usage Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "agentgateway_gen_ai_client_token_usage_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GenAI Server Request Duration Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "agentgateway_gen_ai_server_request_duration_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}