apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: k8shelper
  tag: "1.0.0"
spec:
  title: k8shelper
  description: "Kubernetes helper agent deployed through the kagent runtime"
  modelProvider: gemini
  modelName: gemini-2.0-flash
  source:
    image: adminturneddevops/k8shelper:v2